### PR TITLE
Add support for phone numbers with extensions

### PR DESCRIPTION
**Pull request by jerryclinesmith**
Requested in issue #57 and #78, this pull request adds support for phone numbers with extensions.

Leveraging some code from the "phone" gem, I'm basically extracting the extension, running the normal code using Phony, then adding the extension back at the end.

```
"+31 (0)30 1234 123 x999".phony_normalized # => '31301234123 x999'
"+31 (0)30 1234 123 ext999".phony_normalized # => '31301234123 x999'
"+31 (0)30 1234 123 #999".phony_normalized # => '31301234123 x999'
```

I think there could be more options around formatting, but wanted to gauge interest in accepting the changes first.

### CODE REVIEW

**Comment by joost** [comment]
Seems supernice also. Also here.. we should add your pull request text to the README.

**Comment by jerryclinesmith** [comment]
Comments added, glad to see it pulled in!  Thanks

**Comment by joost** [comment]
Sorry, your other PR introduced some conflicts :| :)

**Comment by jerryclinesmith** [comment]
Should be fixed now...

**Pull request merged**
